/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ulich;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class JPanelRapport extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRapport
     */
    public JPanelRapport() {
        initComponents();
        
         this.setLayout(new BorderLayout());
        
        this.add(jPanelRapport1, BorderLayout.NORTH);
        JPanel panelCentre = new JPanel(new GridBagLayout());
        panelCentre.setBackground(new Color(251,252,210));
        panelCentre.add(jPanelRapport2);
        this.add(panelCentre, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRapport1 = new javax.swing.JPanel();
        jLabelOperation = new javax.swing.JLabel();
        jPanelRapport2 = new javax.swing.JPanel();
        jLabelFormat = new javax.swing.JLabel();
        jLabelPeriode = new javax.swing.JLabel();
        jComboBoxPeriode2 = new javax.swing.JComboBox<>();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jLabelTiret = new javax.swing.JLabel();
        jComboBoxPeriode1 = new javax.swing.JComboBox<>();
        jButtonGenerer = new javax.swing.JButton();
        jButtonImprimer = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(528, 484));

        jPanelRapport1.setBackground(new java.awt.Color(251, 252, 210));
        jPanelRapport1.setLayout(new java.awt.GridBagLayout());

        jLabelOperation.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabelOperation.setForeground(new java.awt.Color(153, 51, 0));
        jLabelOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOperation.setText("Papport Des Opérations");
        jLabelOperation.setPreferredSize(new java.awt.Dimension(450, 89));
        jPanelRapport1.add(jLabelOperation, new java.awt.GridBagConstraints());

        jPanelRapport2.setBackground(new java.awt.Color(251, 252, 210));

        jLabelFormat.setBackground(new java.awt.Color(251, 250, 210));
        jLabelFormat.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelFormat.setText("Format");

        jLabelPeriode.setBackground(new java.awt.Color(251, 252, 210));
        jLabelPeriode.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelPeriode.setText("Période");

        jComboBoxPeriode2.setBackground(new java.awt.Color(251, 252, 210));
        jComboBoxPeriode2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBoxPeriode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriode2ActionPerformed(evt);
            }
        });

        jComboBoxFormat.setBackground(new java.awt.Color(251, 252, 210));
        jComboBoxFormat.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBoxFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "EXCEL", "WORD" }));
        jComboBoxFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatActionPerformed(evt);
            }
        });

        jLabelTiret.setBackground(new java.awt.Color(251, 252, 210));
        jLabelTiret.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTiret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTiret.setText("-");

        jComboBoxPeriode1.setBackground(new java.awt.Color(251, 252, 210));
        jComboBoxPeriode1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBoxPeriode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriode1ActionPerformed(evt);
            }
        });

        jButtonGenerer.setBackground(new java.awt.Color(251, 252, 210));
        jButtonGenerer.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonGenerer.setText("Générer");

        jButtonImprimer.setBackground(new java.awt.Color(251, 252, 210));
        jButtonImprimer.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonImprimer.setText("Imprimer");

        javax.swing.GroupLayout jPanelRapport2Layout = new javax.swing.GroupLayout(jPanelRapport2);
        jPanelRapport2.setLayout(jPanelRapport2Layout);
        jPanelRapport2Layout.setHorizontalGroup(
            jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRapport2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPeriode, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPeriode1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRapport2Layout.createSequentialGroup()
                        .addComponent(jLabelTiret, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPeriode2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelRapport2Layout.setVerticalGroup(
            jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRapport2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabelPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPeriode2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTiret)
                    .addComponent(jComboBoxPeriode1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelRapport2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonGenerer)
                .addGap(28, 28, 28)
                .addComponent(jButtonImprimer)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRapport1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelRapport2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRapport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRapport2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPeriode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeriode2ActionPerformed

    private void jComboBoxFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFormatActionPerformed

    private void jComboBoxPeriode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeriode1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerer;
    private javax.swing.JButton jButtonImprimer;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JComboBox<String> jComboBoxPeriode1;
    private javax.swing.JComboBox<String> jComboBoxPeriode2;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelOperation;
    private javax.swing.JLabel jLabelPeriode;
    private javax.swing.JLabel jLabelTiret;
    private javax.swing.JPanel jPanelRapport1;
    private javax.swing.JPanel jPanelRapport2;
    // End of variables declaration//GEN-END:variables
}
