/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ulich;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class JPanelConnection extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConnection
     */
    public JPanelConnection() {
        initComponents();
        
        this.setLayout(new BorderLayout());
        
        this.add(jPanelRenseigner, BorderLayout.NORTH);
        JPanel panelCentre = new JPanel(new GridBagLayout());
        panelCentre.setBackground(new Color(251,252,210));
        panelCentre.add(jPanelformulaire);
        this.add(panelCentre, BorderLayout.CENTER);
        
    
        
        styliserBouton(jButtonConnection);
        styliserBouton(jButtonAnnuler);
        styliserComboBox(jComboBoxFonction);
    }   
    
    private void styliserBouton(JButton btn) {
            Color customColor = new Color(251, 252, 210);
            btn.setBackground(customColor);
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setContentAreaFilled(true);
            btn.setOpaque(true);
        }
        
        private void styliserComboBox(JComboBox comboBox) {
        Color customColor = new Color(251, 252, 210);
        comboBox.setBackground(customColor);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelformulaire = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jTextField1Nom = new javax.swing.JTextField();
        jLabelPrenoms = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabelFonction = new javax.swing.JLabel();
        jLabelMotDePasse = new javax.swing.JLabel();
        jComboBoxFonction = new javax.swing.JComboBox<>();
        jPasswordFieldMotDePasse = new javax.swing.JPasswordField();
        jButtonConnection = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jPanelRenseigner = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 253, 210));
        setPreferredSize(new java.awt.Dimension(528, 484));

        jPanelformulaire.setBackground(new java.awt.Color(251, 252, 210));

        jLabelNom.setBackground(new java.awt.Color(251, 252, 210));
        jLabelNom.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelNom.setText("Nom");

        jTextField1Nom.setBackground(new java.awt.Color(251, 252, 210));
        jTextField1Nom.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabelPrenoms.setBackground(new java.awt.Color(251, 252, 210));
        jLabelPrenoms.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelPrenoms.setText("Prénoms");

        jTextFieldPrenom.setBackground(new java.awt.Color(251, 252, 210));
        jTextFieldPrenom.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jLabelFonction.setBackground(new java.awt.Color(251, 252, 210));
        jLabelFonction.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelFonction.setText("Fonction");

        jLabelMotDePasse.setBackground(new java.awt.Color(251, 252, 210));
        jLabelMotDePasse.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelMotDePasse.setText("Mot de Passe");

        jComboBoxFonction.setBackground(new java.awt.Color(251, 252, 210));
        jComboBoxFonction.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBoxFonction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir...", "Prêtre", "Secrétaire", "Admin" }));

        jPasswordFieldMotDePasse.setBackground(new java.awt.Color(250, 251, 210));
        jPasswordFieldMotDePasse.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jButtonConnection.setBackground(new java.awt.Color(251, 253, 210));
        jButtonConnection.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonConnection.setForeground(new java.awt.Color(153, 51, 0));
        jButtonConnection.setText("Se connecter");
        jButtonConnection.setBorder(null);
        jButtonConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectionActionPerformed(evt);
            }
        });

        jButtonAnnuler.setBackground(new java.awt.Color(251, 252, 210));
        jButtonAnnuler.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonAnnuler.setForeground(new java.awt.Color(153, 51, 0));
        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(251, 252, 210), new java.awt.Color(251, 252, 210), new java.awt.Color(251, 252, 210), new java.awt.Color(251, 252, 210)));
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelformulaireLayout = new javax.swing.GroupLayout(jPanelformulaire);
        jPanelformulaire.setLayout(jPanelformulaireLayout);
        jPanelformulaireLayout.setHorizontalGroup(
            jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelformulaireLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanelformulaireLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButtonConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelformulaireLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPrenoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFonction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(70, 70, 70)
                    .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordFieldMotDePasse)
                        .addComponent(jTextFieldPrenom)
                        .addComponent(jTextField1Nom)
                        .addComponent(jComboBoxFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        jPanelformulaireLayout.setVerticalGroup(
            jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelformulaireLayout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelformulaireLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelformulaireLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jTextField1Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(30, 30, 30)
                    .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelformulaireLayout.createSequentialGroup()
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelformulaireLayout.createSequentialGroup()
                            .addComponent(jLabelPrenoms, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)))
                    .addGap(30, 30, 30)
                    .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanelformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        jPanelRenseigner.setBackground(new java.awt.Color(251, 252, 210));
        jPanelRenseigner.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Veuillez renseignez ces champs");
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 89));
        jPanelRenseigner.add(jLabel2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRenseigner, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            .addComponent(jPanelformulaire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRenseigner, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelformulaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jButtonConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectionActionPerformed
        connecterUtilisateur();
        Renseigner fenetre= new Renseigner();
        fenetre.setVisible(true);
        
        java.awt.Window window=javax.swing.SwingUtilities.getWindowAncestor(JPanelConnection.this);
        if(window != null){
            window.dispose();
        }
    }//GEN-LAST:event_jButtonConnectionActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        annulerConnection();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed


    /*private void setResizable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonConnection;
    private javax.swing.JComboBox<String> jComboBoxFonction;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFonction;
    private javax.swing.JLabel jLabelMotDePasse;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenoms;
    private javax.swing.JPanel jPanelRenseigner;
    private javax.swing.JPanel jPanelformulaire;
    private javax.swing.JPasswordField jPasswordFieldMotDePasse;
    private javax.swing.JTextField jTextField1Nom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables

    private void connecterUtilisateur() {
    // Récupérer les valeurs
    String nom = jTextField1Nom.getText().trim();
    String prenom = jTextFieldPrenom.getText().trim();
    String fonction = (String) jComboBoxFonction.getSelectedItem();
    String motDePasse = new String(jPasswordFieldMotDePasse.getPassword());
    
    // Validation simple
    if (nom.isEmpty() || prenom.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez saisir nom et prénom", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if ("Choisir...".equals(fonction)) {
        JOptionPane.showMessageDialog(this, "Veuillez choisir une fonction", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Vérification basique (à adapter)
    if (verifierConnexion(nom, prenom, fonction, motDePasse)) {
        JOptionPane.showMessageDialog(this, 
            "Connexion réussie!\nBienvenue " + prenom + " " + nom, 
            "Succès", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Rediriger vers l'application principale
        redirigerVersApplication(fonction);
    } else {
        JOptionPane.showMessageDialog(this, "Identifiants incorrects", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}

private boolean verifierConnexion(String nom, String prenom, String fonction, String motDePasse) {
    // Exemple simple - à remplacer par votre vraie logique
    return !motDePasse.isEmpty(); // Accepte tout mot de passe non vide pour tester
}

private void redirigerVersApplication(String fonction) {
    // Cacher ce panel
    this.setVisible(false);
    
    // Trouver la fenêtre parente et la fermer
    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (parentWindow != null) {
        parentWindow.dispose();
    }
    
    // Ouvrir la fenêtre principale selon le rôle
    // Exemple: new FenetrePrincipale(fonction).setVisible(true);
}

    private void annulerConnection() {
        
        Object[] options={"Oui","Nom"};
        // Demander confirmation
        int confirmation = JOptionPane.showOptionDialog(this,
            "Voulez-vous vraiment annuler la connexion ?\nTous les champs seront effacés.",
            "Confirmation d'annulation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
                null,
        options,
        options[0]
        );
        if (confirmation == JOptionPane.YES_OPTION) {
            // Vider tous les champs
            jTextField1Nom.setText("");
            jTextFieldPrenom.setText("");
            jComboBoxFonction.setSelectedIndex(0); // Remettre à "Choi
            jPasswordFieldMotDePasse.setText("");

            JOptionPane.showMessageDialog(this,
                "Connexion annulée\nChamps réinitialisés",
                "Annulation",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
}
