/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ulich;

import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;




/**
 *
 * @author HP
 */
public class MainUli extends javax.swing.JFrame {
    

    /**
     * Creates new form MainUli
     */
    // --------------------- AKOUETE EST PASSER PAR ICI ------------------
    public MainUli() {
        initComponents();
        // --- début à coller juste après initComponents(); ---
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        final int maxW = (int) (screenSize.width * 0.9);   // 90% de l'écran
        final int maxH = (int) (screenSize.height * 0.9);  // 90% de l'écran

        // tu peux ajuster la taille minimale si tu veux
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(true);

        // Certains environnements n'appliquent pas setMaximumSize -> on force via un listener
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int w = getWidth();
                int h = getHeight();
                int newW = Math.min(w, maxW);
                int newH = Math.min(h, maxH);
                if (w != newW || h != newH) {
                    setSize(newW, newH);
                }
            }
        });
        // reprotege l'affichage des préférences
        pack();
        setLocationRelativeTo(null);
        // --- fin ---
        
        this.setLayout(new BorderLayout());
        
        //BARRE VERTICALE OUEST
        jPanelUli1.setPreferredSize(new Dimension(150,0));
        this.add(jPanelUli1, BorderLayout.WEST);
       
        //BARRE HORIZONTALE NORD
        JPanel panelDroite = new JPanel(new BorderLayout());
    this.add(panelDroite, BorderLayout.CENTER);
        jPanelBienvenue.setPreferredSize(new Dimension(0,90));
        panelDroite.add(jPanelBienvenue, BorderLayout.NORTH);
        
        //PANEL CENTRAL CONTENU
        panelDroite.add(jPanelContenu, BorderLayout.CENTER);
        jPanelContenu.setBackground(new Color(251,252,210));
        jPanelContenu.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        //label avec photo
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 0.9; // 90% de l'espace pour la photo
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.fill = GridBagConstraints.NONE; // 
        gbc.insets = new Insets(10, 20, 20, 20);
        jPanelContenu.add(jLabelPhoto, gbc); 
        
        // Pour le label avec texte
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 0.1; // 10% pour le texte
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.NONE; 
        gbc.insets = new Insets(30, 20, 0, 20);
        jPanelContenu.add(jLabelDans, gbc); // 

        
        
        // Timer de 5 secondes avant de charger la page de connexion
        Timer timer = new Timer(5000, e -> afficherPageConnexion());
        timer.setRepeats(false);
        timer.start();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUli1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBienvenue = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelContenu = new javax.swing.JPanel();
        jLabelDans = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelUli1.setBackground(new java.awt.Color(153, 51, 0));
        jPanelUli1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelUli1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ULI");
        jPanelUli1.add(jLabel1, new java.awt.GridBagConstraints());

        jPanelBienvenue.setBackground(new java.awt.Color(251, 252, 210));
        jPanelBienvenue.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 90)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenue");
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 89));
        jPanelBienvenue.add(jLabel2, new java.awt.GridBagConstraints());

        jPanelContenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDans.setFont(new java.awt.Font("Vivaldi", 0, 70)); // NOI18N
        jLabelDans.setForeground(new java.awt.Color(153, 51, 0));
        jLabelDans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDans.setText("Dans Uli Application");

        javax.swing.GroupLayout jPanelContenuLayout = new javax.swing.GroupLayout(jPanelContenu);
        jPanelContenu.setLayout(jPanelContenuLayout);
        jPanelContenuLayout.setHorizontalGroup(
            jPanelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDans, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContenuLayout.setVerticalGroup(
            jPanelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenuLayout.createSequentialGroup()
                .addComponent(jLabelDans, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelUli1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelContenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDans;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JPanel jPanelBienvenue;
    private javax.swing.JPanel jPanelContenu;
    private javax.swing.JPanel jPanelUli1;
    // End of variables declaration//GEN-END:variables

    private void afficherPageConnexion() {
    // Vider le panel contenu
    jPanelContenu.removeAll();
    jPanelContenu.setLayout(new BorderLayout());

    // Créer ton panel de connexion
    JPanelConnection panelConnexion = new JPanelConnection();

    // L'ajouter dans le centre
    jPanelContenu.setLayout(new BorderLayout());
    jPanelContenu.add(panelConnexion, BorderLayout.CENTER);

    // Rafraîchir
    jPanelContenu.revalidate();
    jPanelContenu.repaint();


    }
}
