/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ulich;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class Operation extends javax.swing.JPanel {

    /**
     * Creates new form Operation
     */
    public Operation() {
        initComponents();
        
        this.setLayout(new BorderLayout());
        
        this.add(jPanelEnTete, BorderLayout.NORTH);
        JPanel panelCentre = new JPanel(new GridBagLayout());
        panelCentre.setBackground(new Color(251,252,210));
        panelCentre.add(jPanelOpe);
        this.add(panelCentre, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEnTete = new javax.swing.JPanel();
        jLabelOperation = new javax.swing.JLabel();
        jPanelOpe = new javax.swing.JPanel();
        jLabelType = new javax.swing.JLabel();
        jLabelMontant = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelMotif = new javax.swing.JLabel();
        jTextFieldMontant = new javax.swing.JTextField();
        jTextFieldMotif = new javax.swing.JTextField();
        jComboBoxType = new javax.swing.JComboBox<>();
        jTextFieldDate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(528, 484));

        jPanelEnTete.setBackground(new java.awt.Color(251, 252, 210));
        jPanelEnTete.setLayout(new java.awt.GridBagLayout());

        jLabelOperation.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabelOperation.setForeground(new java.awt.Color(153, 51, 0));
        jLabelOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOperation.setText("Opération");
        jLabelOperation.setPreferredSize(new java.awt.Dimension(450, 89));
        jPanelEnTete.add(jLabelOperation, new java.awt.GridBagConstraints());

        jPanelOpe.setBackground(new java.awt.Color(251, 252, 210));
        jPanelOpe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelType.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelType.setText("Type");

        jLabelMontant.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelMontant.setText("Montant");

        jLabelDate.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelDate.setText("Date");

        jLabelMotif.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelMotif.setText("Motif");

        jTextFieldMontant.setBackground(new java.awt.Color(251, 252, 210));
        jTextFieldMontant.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextFieldMontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontantActionPerformed(evt);
            }
        });

        jTextFieldMotif.setBackground(new java.awt.Color(251, 252, 210));
        jTextFieldMotif.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextFieldMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotifActionPerformed(evt);
            }
        });

        jComboBoxType.setBackground(new java.awt.Color(251, 252, 210));
        jComboBoxType.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir...", "Entrée", "Sortie", " " }));

        jTextFieldDate.setBackground(new java.awt.Color(251, 252, 210));
        jTextFieldDate.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jButton2.setBackground(new java.awt.Color(251, 252, 210));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 0));
        jButton2.setText("Annuler");
        jButton2.setBorder(null);

        jButton3.setBackground(new java.awt.Color(251, 252, 210));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 51, 0));
        jButton3.setText("Valider");
        jButton3.setBorder(null);

        javax.swing.GroupLayout jPanelOpeLayout = new javax.swing.GroupLayout(jPanelOpe);
        jPanelOpe.setLayout(jPanelOpeLayout);
        jPanelOpeLayout.setHorizontalGroup(
            jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpeLayout.createSequentialGroup()
                .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOpeLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMontant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMotif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelOpeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addGap(68, 68, 68))
        );
        jPanelOpeLayout.setVerticalGroup(
            jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpeLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelOpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEnTete, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelOpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEnTete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotifActionPerformed

    private void jTextFieldMontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelMontant;
    private javax.swing.JLabel jLabelMotif;
    private javax.swing.JLabel jLabelOperation;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelEnTete;
    private javax.swing.JPanel jPanelOpe;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldMontant;
    private javax.swing.JTextField jTextFieldMotif;
    // End of variables declaration//GEN-END:variables
}
