/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ulich;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class Renseigner extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private Operation panelOperation;
    private JPanelRapport panelRapport;
    private JPanelCaisse panelCaisse;


    /**
     * Creates new form Renseigner
     */
    public Renseigner() {
        initComponents();
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        final int maxW = (int) (screenSize.width * 0.9);   // 90% de l'écran
        final int maxH = (int) (screenSize.height * 0.9);  // 90% de l'écran

        // tu peux ajuster la taille minimale si tu veux
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(true);

        // Certains environnements n'appliquent pas setMaximumSize -> on force via un listener
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int w = getWidth();
                int h = getHeight();
                int newW = Math.min(w, maxW);
                int newH = Math.min(h, maxH);
                if (w != newW || h != newH) {
                    setSize(newW, newH);
                }
            }
        });
        // reprotege l'affichage des préférences
        pack();
        setLocationRelativeTo(null);
        // --- fin ---
        
        /*Timer timer = new Timer(5000, e -> afficherPageOperation());
        timer.setRepeats(false);
        timer.start();*/
        
        cardLayout = new CardLayout();
        jPanelAction.setLayout(cardLayout);
        
        panelOperation = new Operation();
        panelRapport = new JPanelRapport();
        panelCaisse = new JPanelCaisse();
        
        jPanelAction.add(panelOperation, "operation");
        jPanelAction.add(panelRapport, "rapport");
        jPanelAction.add(panelCaisse, "caisse");
        
        jButtonCaisse.addActionListener(e -> {
        cardLayout.show(jPanelAction, "caisse");
        });
        jButtonRapport.addActionListener(e -> {
        cardLayout.show(jPanelAction, "rapport");
        });
        jButtonOperation.addActionListener(e -> {
        cardLayout.show(jPanelAction, "Operation");
        });
    }
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelTablBord = new javax.swing.JPanel();
        jPanelAcceuil = new javax.swing.JPanel();
        jLabelAccueil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButtonRapport = new javax.swing.JButton();
        jButtonCaisse = new javax.swing.JButton();
        jButtonOperation = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonDeconnecter = new javax.swing.JButton();
        jPanelAction = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 658));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanelTablBord.setBackground(new java.awt.Color(204, 102, 0));
        jPanelTablBord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 5));
        jPanelTablBord.setLayout(new java.awt.BorderLayout());

        jPanelAcceuil.setBackground(new java.awt.Color(153, 102, 0));
        jPanelAcceuil.setOpaque(false);

        jLabelAccueil.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabelAccueil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAccueil.setText("Accueil");

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setLayout(new java.awt.BorderLayout(1, 4));

        jButtonRapport.setBackground(new java.awt.Color(204, 102, 0));
        jButtonRapport.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonRapport.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRapport.setText("Générer un rapport");
        jButtonRapport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0)));

        jButtonCaisse.setBackground(new java.awt.Color(204, 102, 0));
        jButtonCaisse.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonCaisse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCaisse.setText("Solde de la caisse");
        jButtonCaisse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0)));
        jButtonCaisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaisseActionPerformed(evt);
            }
        });

        jButtonOperation.setBackground(new java.awt.Color(204, 102, 0));
        jButtonOperation.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonOperation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOperation.setText("Faire une opération");
        jButtonOperation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0)));
        jButtonOperation.setOpaque(true);
        jButtonOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperationActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        jButtonDeconnecter.setBackground(new java.awt.Color(204, 102, 0));
        jButtonDeconnecter.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonDeconnecter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeconnecter.setText("Se déconnecter");
        jButtonDeconnecter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonDeconnecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonDeconnecter, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAcceuilLayout = new javax.swing.GroupLayout(jPanelAcceuil);
        jPanelAcceuil.setLayout(jPanelAcceuilLayout);
        jPanelAcceuilLayout.setHorizontalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccueil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonRapport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(jButtonCaisse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAcceuilLayout.setVerticalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                .addComponent(jLabelAccueil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButtonCaisse, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButtonRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTablBord.add(jPanelAcceuil, java.awt.BorderLayout.CENTER);

        jPanelAction.setBackground(new java.awt.Color(251, 252, 210));
        jPanelAction.setPreferredSize(new java.awt.Dimension(528, 812));

        javax.swing.GroupLayout jPanelActionLayout = new javax.swing.GroupLayout(jPanelAction);
        jPanelAction.setLayout(jPanelActionLayout);
        jPanelActionLayout.setHorizontalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jPanelActionLayout.setVerticalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanelTablBord, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTablBord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelAction, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOperationActionPerformed

    private void jButtonCaisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaisseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCaisseActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaisse;
    private javax.swing.JButton jButtonDeconnecter;
    private javax.swing.JButton jButtonOperation;
    private javax.swing.JButton jButtonRapport;
    private javax.swing.JLabel jLabelAccueil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAcceuil;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelTablBord;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /*private Timer afficherPageOperation() {
        // Vider le panel contenu
    jPanelAction.removeAll();
    jPanelAction.setLayout(new BorderLayout());

    // Créer ton panel de connexion
    JPanelRapport panelOperation = new JPanelRapport();

    // L'ajouter dans le centre
    jPanelAction.setLayout(new BorderLayout());
    jPanelAction.add(panelOperation, BorderLayout.CENTER);

    // Rafraîchir
    jPanelAction.revalidate();
    jPanelAction.repaint();
        return null;

    }*/
}

